# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyjsonl" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "01e2e48a8f56720a8a898933eb4fd77d020de4d3a96426b5d2f6363e524cbed0"
      url "https://github.com/xZhad/lazyjsonl/releases/download/v#{version}/lazyjsonl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dfee9609d2649ef2d1365d9d0c19cee1d99c45455b9bab05c98ccd4f903e9b3b"
      url "https://github.com/xZhad/lazyjsonl/releases/download/v#{version}/lazyjsonl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cce2866aca6e7eb7b023711f75e7e8f7966ead78ca7e5e2fad6e8a03b861cde3"
      url "https://github.com/xZhad/lazyjsonl/releases/download/v#{version}/lazyjsonl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c9d71a31e74cb3e4488582209303c82aeb3adea613c91fd31f8b6700c46a19f7"
      url "https://github.com/xZhad/lazyjsonl/releases/download/v#{version}/lazyjsonl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lazyjsonl"
  desc "Terminal UI for inspecting, filtering, and managing JSONL files — like lazygit for structured data"
  homepage "https://github.com/xZhad/lazyjsonl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyjsonl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyjsonl"]
    end
  end

  # No zap stanza required

end
