# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyjsonl" do
  version "0.16.2"

  on_macos do
    on_intel do
      sha256 "89da40cbbefbce1b63a838de0adb1a35867edfccd368f44aca77b24870c0a330"
      url "https://github.com/xZhad/lazyjsonl/releases/download/v#{version}/lazyjsonl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b17ab4b526b341739e772490db4fa109fa4db06f5296fb3d494b33ce95f9f301"
      url "https://github.com/xZhad/lazyjsonl/releases/download/v#{version}/lazyjsonl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "96eb3b263fccae16680b7a7056dbe65c99461f1b92369fbdff69267cb9de8a1c"
      url "https://github.com/xZhad/lazyjsonl/releases/download/v#{version}/lazyjsonl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a2d51a5e20b5b32d7e776050204e4938c3a715f8e9f8b892f1f9820642606c7"
      url "https://github.com/xZhad/lazyjsonl/releases/download/v#{version}/lazyjsonl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lazyjsonl"
  desc "Terminal UI for inspecting, filtering, and managing JSONL files — like lazygit for structured data"
  homepage "https://github.com/xZhad/lazyjsonl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyjsonl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyjsonl"]
    end
  end

  # No zap stanza required

end
