# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyjsonl" do
  version "0.15.0"

  on_macos do
    on_intel do
      sha256 "2d5c886eaee60d5b597364be7bd0226720d00db0aca3ef077fc7c7431c5d1a3e"
      url "https://github.com/xZhad/lazyjsonl/releases/download/v#{version}/lazyjsonl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "42608223529283c4d0606401d0fc256b576dbe20715e7b1019ed9eea84747c25"
      url "https://github.com/xZhad/lazyjsonl/releases/download/v#{version}/lazyjsonl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b40a607bfac82714f6ab5608f433731dcdfd9dffaceb6782fecb3412471d5152"
      url "https://github.com/xZhad/lazyjsonl/releases/download/v#{version}/lazyjsonl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e8a32cc8588865255cc9cf4cdf034e78332245db04f0ca1400630c5b67c3afa8"
      url "https://github.com/xZhad/lazyjsonl/releases/download/v#{version}/lazyjsonl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lazyjsonl"
  desc "Terminal UI for inspecting, filtering, and managing JSONL files — like lazygit for structured data"
  homepage "https://github.com/xZhad/lazyjsonl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyjsonl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyjsonl"]
    end
  end

  # No zap stanza required

end
