# This file was generated by GoReleaser. DO NOT EDIT.
cask "pomo" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "c3ee6e3b3a2780c5ed21be3f536923934d922a6e6c31fec1bf815a847c008d67"
      url "https://github.com/xZhad/pomo/releases/download/v#{version}/pomo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7510f72e6d442ee0d21322f0f0a06f6698de98699fad65849290f6a0523a72b2"
      url "https://github.com/xZhad/pomo/releases/download/v#{version}/pomo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "181fa64b704d2f7cee961ff90e7addd091c18f5eec5cf1e84353ca45c8550ce0"
      url "https://github.com/xZhad/pomo/releases/download/v#{version}/pomo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c9b07032298332f7a751869fde11a729c5064f4d9187b4a5bb82443ab900941"
      url "https://github.com/xZhad/pomo/releases/download/v#{version}/pomo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pomo"
  desc "Terminal pomodoro timer with session logging, notes, and an animated TUI"
  homepage "https://github.com/xZhad/pomo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pomo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pomo"]
    end
  end

  # No zap stanza required

end
