# This file was generated by GoReleaser. DO NOT EDIT.
cask "pomo" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "6759c63e3a468063a00f57d3e309cbd2c165c56dd9b2dce45d135d315cfe2597"
      url "https://github.com/xZhad/pomo/releases/download/v#{version}/pomo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1166c3f98ff645301424d8511e20d4d4d710ac79da4fd8daf86de34fc5d5b069"
      url "https://github.com/xZhad/pomo/releases/download/v#{version}/pomo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4af81db3ad60edd30aad9a47fd6a6482814a2eec5f7157d04fb122211f6afff1"
      url "https://github.com/xZhad/pomo/releases/download/v#{version}/pomo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "41239c2c6484555165612d9c2a58f043e03f3d847876ce3a2f864f76627df2a9"
      url "https://github.com/xZhad/pomo/releases/download/v#{version}/pomo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pomo"
  desc "Terminal pomodoro timer with session logging, notes, and an animated TUI"
  homepage "https://github.com/xZhad/pomo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pomo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pomo"]
    end
  end

  # No zap stanza required

end
