# This file was generated by GoReleaser. DO NOT EDIT.
cask "pomo" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "7917a6d471f8c9489f4d673ad95c09168a22ad2537579be40821d6f84412f03a"
      url "https://github.com/xZhad/pomo/releases/download/v#{version}/pomo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b2df3fa3276d2f8bf16de02fa30e0644ae5469d2fe0a23f4a8bb911879803f01"
      url "https://github.com/xZhad/pomo/releases/download/v#{version}/pomo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6836fdb34ff9bd48e03d33ea74d27b6b54d35a4e0b1dbaffc01335f109048110"
      url "https://github.com/xZhad/pomo/releases/download/v#{version}/pomo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c9ffaee59b22d81da1a6489b1f34bc17c9f4ea2e154ce3b83cf1f0e1cc75bd6"
      url "https://github.com/xZhad/pomo/releases/download/v#{version}/pomo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pomo"
  desc "Terminal pomodoro timer with session logging, notes, and an animated TUI"
  homepage "https://github.com/xZhad/pomo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pomo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pomo"]
    end
  end

  # No zap stanza required

end
